In [1]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()

A, A + B  # element wise operation: 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [2]:
# Hadamard product or elementwise multiplication
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [3]:
a = 5
A, A + a, A * a

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]),
 tensor([[ 0.,  5., 10., 15.],
         [20., 25., 30., 35.],
         [40., 45., 50., 55.],
         [60., 65., 70., 75.],
         [80., 85., 90., 95.]]))

In [4]:
# Reduction operations
X = torch.arange(5)
X, X.sum()

(tensor([0, 1, 2, 3, 4]), tensor(10))

In [5]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [6]:
A, A.sum(axis=0), A.sum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 tensor([ 6., 22., 38., 54., 70.]))

In [7]:
A.mean(), A.sum() / A.numel(), A.numel()

(tensor(9.5000), tensor(9.5000), 20)

In [8]:
A.mean(axis=1)

tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000])

In [9]:
A.sum(axis=1, keepdim=True), A.sum(axis=1, keepdim=True).shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [10]:
# getting the cumulative sum
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [13]:
# Matrix-scalar dot product
x = torch.arange(4, dtype=torch.float)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [14]:
# Matrix-vector product
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [17]:
# Matrix-matrix multiplication
C = torch.ones(4, 2)
A, C, torch.mm(A, C)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[ 6.,  6.],
         [22., 22.],
         [38., 38.],
         [54., 54.],
         [70., 70.]]))

In [22]:
# norms
# L2 norm
X = torch.tensor([3.0, -8.0])
torch.norm(X)

tensor(8.5440)

In [23]:
# L1 norm
torch.abs(X).sum()

tensor(11.)

Frobenius Norm
$$ \left \| X \right \|_F = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}x^2_{ij}} $$

In [24]:
# Frobenius Norm
torch.norm(A)

tensor(49.6991)